### PR TITLE
Add Rust example

### PR DESCRIPTION
**Pull request by Tiwalun**
As promised in #74, here is a Rust example program for the Fomu softcore.

It is a copy of the riscv-blink program, converted to Rust. USB is not yet supported,
so you have to remove the Fomu and plug it in again so you can program it again.

Thanks to @david-sawatzke for the nice new peripheral access crate (https://crates.io/crates/fomu-pac) as well!

### CODE REVIEW

**Comment by david-sawatzke** [comment]
Doesn't work on `Fomu PVT running DFU Bootloader v2.0.3` (the led flashes red, seems to be an error state), but works on 1.9.1 . We (currently) have no idea why.

**Comment by mithro** [comment]
@xobs - Any idea?

**Comment by mithro** [comment]
@Tiwalun and @david-sawatzke -- If you are still at #36C3, I'd be happy to give you some more Fomu's to share with other rust people.

**Comment by Tiwalun** [comment]
It seems that the linker script in the fomu-rt crate had an issue, the flash start address was different than in the C code examples in the workshop repo.

I've made a PR to fix this: im-tomu/fomu-rt#1

@david-sawatzke and everyone else, please try this on you fomus to see if it now works.

:warning: The PR currently has a patched dependency for the fomu-rt crate, which should be removed when fomu-rt is fixed, and before merging this.

**Comment by david-sawatzke** [comment]
@tiwalun Great find, works fine for me now.

I've also improved lxsdocs a bit and the svd now has proper access restrictions, proper sizes & some other changes, but that means it doesn't build with the current fomu-pac version.

**Comment by mithro** [comment]
I'll leave @xobs to review and merge this change.

**Comment by xobs** [comment]
`fomu-rt` is now fixed, so @Tiwalun can remove the patch, and I'll merge this.

**Pull request merged**
