### PR TITLE
Add example of changing LED color with wishbone-tool

### PR DESCRIPTION
**Pull request by pdp7**
Add examples of changing color using wishbone-tool and fomu_rgb_output CSR:
```
   $ wishbone-tool 0x60003000 0x1 # make LED green
   $ wishbone-tool 0x60003000 0x2 # make LED red
   $ wishbone-tool 0x60003000 0x3 # make LED yellow   
   $ wishbone-tool 0x60003000 0x4 # make LED blue
   $ wishbone-tool 0x60003000 0x5 # make LED teal
   $ wishbone-tool 0x60003000 0x6 # make LED pink
   $ wishbone-tool 0x60003000 0x7 # make LED white
```
NOTE: I have a different address for the CSR so I changed the tutorial to match:
```
pdp7@x1:~/dev/fpga/fomu-workshop/litex/build$ cat csr.csv 
#--------------------------------------------------------------------------------
# Auto-generated by Migen (e2e6c72) & LiteX (f0b5c672) on 2020-03-02 15:51:45
#--------------------------------------------------------------------------------
csr_base,timer0,0x60002800,,
csr_base,fomu_rgb,0x60003000,,
csr_register,timer0_load,0x60002800,4,rw
csr_register,timer0_reload,0x60002810,4,rw
csr_register,timer0_en,0x60002820,1,rw
csr_register,timer0_update_value,0x60002824,1,rw
csr_register,timer0_value,0x60002828,4,ro
csr_register,timer0_ev_status,0x60002838,1,rw
csr_register,timer0_ev_pending,0x6000283c,1,rw
csr_register,timer0_ev_enable,0x60002840,1,rw
csr_register,fomu_rgb_output,0x60003000,1,rw
constant,config_clock_frequency,12000000,,
constant,config_cpu_type,none,,
constant,config_cpu_type_none,None,,
constant,config_csr_alignment,32,,
constant,config_csr_data_width,8,,
constant,config_shadow_base,2147483648,,
memory_region,csr,0x60000000,65536,cached
memory_region,sram,0x10000000,131072,cached

```

### CODE REVIEW

**Comment by pdp7** [comment]
@xobs @mithro fyi - the build for Read The Docs fails:
https://readthedocs.org/projects/fomu-workshop/builds/10536631/
`Command killed due to excessive memory consumption`
Screenshot from 2020-03-02 16-04-25

**Comment by xobs** [comment]
Something must have changed upstream in litex.

The CPU we have treats values with addresses `0xb0000000`, `0xe0000000`, and `0xf0000000` as "IO", and consequently doesn't cache them.  That's not an issue in the current implementation as it has no dcache, but if a cache were added that could become an issue.

Litex mirrors everything below 0x80000000 above 0x80000000.  So your `csr_base,timer0,0x60002800,,` has an uncached couterpoint at `0xe0002800`, which is preferrable as it will not get cached.

Caching io ranges gets very, very spooky.

Litex used to output the correct values in csr.csv, and currently does so in the foboot build.  Perhaps we need to update the `litex-boards` repo.

**Comment by pdp7** [comment]
@xobs could it be because I'm also doing development on litex for the hadbadge?  Maybe the versions installed in my python too new?  I wasn't sure how much the different installations of litex I have are kept separate.  I assumed it has to do with what version is installed with 'setup.py install'?

**Comment by xobs** [comment]
> @xobs could it be because I'm also doing development on litex for the hadbadge? Maybe the versions installed in my python too new? I wasn't sure how much the different installations of litex I have are kept separate. I assumed it has to do with what version is installed with 'setup.py install'?

I tend to avoid `setup.py` for a number of reasons.  I use `lxbuildenv.py` which vendors everything under a `deps` directory, which is how the separation happens.

If you're using litex on the hadbadge, you'll definitely want to check the flags for your memory regions when you generate your block.  You want to make sure those regions are uncached, because I believe the hadbadge core does have csrs.

Incidentally, you may be interested in `wishbone-tool -s terminal`, and then instantiating your BaseSoC in litex with `uart_name="crossover"`.  That will give you an interactive terminal over the bridge, which is at least three fewer wires to connect.

**Pull request merged**
