### PR TITLE
ci: add Chisel Blink, use Action setup-scala

### PR DESCRIPTION
**Pull request by ekiwi**
This solves one half of issue https://github.com/im-tomu/fomu-workshop/issues/383

### CODE REVIEW

**Review by umarcor — COMMENTED** [review]
What's the motivation for using two different Actions to setup Java/Scala? It seems that both of them support all three platforms. Should there be a limitation in `actions/setup-java` that requires the other one, I'd suggest using it for all platforms and adding a comment explaining why that is required.

At the same time, the toolchain can be installed locally by using the same script as in CI. The only requirement is Python. What would be the minimal requirements for someone to try this example locally? That is, what's the alternative to setup-java|setup-scala? Note that I don't expect it to be explained here, but to add some reference to Scala/Chisel docs in an upcoming PR.

**Comment by ekiwi** [comment]
> What's the motivation for using two different Actions to setup Java/Scala? It seems that both of them support all three platforms. Should there be a limitation in `actions/setup-java` that requires the other one, I'd suggest using it for all platforms and adding a comment explaining why that is required.

I changed the CI to use `setup-scala` for all OS.

Do you want me to squash my commits?



> At the same time, the toolchain can be installed locally by using the same script as in CI. The only requirement is Python. What would be the minimal requirements for someone to try this example locally? That is, what's the alternative to setup-java|setup-scala? Note that I don't expect it to be explained here, but to add some reference to Scala/Chisel docs in an upcoming PR.

I will keep that in mind. Essentially you just need a recent version of Java (like OpenJDK 11) and the sbt build tool which will in turn download the correct Scala compiler version etc. once you run the build.

**Comment by umarcor** [comment]
> I changed the CI to use `setup-scala` for all OS.

What was the reason to choose that instead of the other?

> Do you want me to squash my commits?

No need, GitHub allows to do it while merging.

**Comment by ekiwi** [comment]
> What was the reason to choose that instead of the other?

On Windows and Ubuntu `sbt` (the scala build tool) seems to be installed, but not on MacOS. ` setup-scala` makes sure that `sbt` is also installed.

**Pull request merged**
