### PR TITLE
Update to zig 0.6.0

### PR DESCRIPTION
**Pull request by daurnimator**
I managed to crash my usb drivers somehow... until I reboot I won't be able to actually test this.
(though if someone else wants to give it a try and confirms it works, then we can merge)

### CODE REVIEW

**Comment by mithro** [comment]
It would be nice if the zig examples where tested on Travis in some way?

**Comment by daurnimator** [comment]
> It would be nice if the zig examples where tested on Travis in some way?

Should be as easy as e.g. `curl -L https://ziglang.org/builds/zig-linux-x86_64-0.6.0.tar.xz | tar -xJf -` and then running `./zig build`. I'm not sure how you've got downloads and caching set up in your travis though: I'm not sure if you want to integrate with get-toolchain.py ?

**Comment by mithro** [comment]
@daurnimator The travis config is at https://github.com/im-tomu/fomu-workshop/blob/master/.travis.yml

**Comment by mithro** [comment]
@daurnimator -- Adding it to `./get-toolchain.py` behind an option seems perfectly reasonable. I'll leave it up to @xobs if he wants the option on or off by default.

**Comment by xobs** [comment]
I'd prefer the option is off by default, but we can certainly look into enabling it by default in the future.

**Pull request merged**
